import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Get directory of this file (works in both Bun and Node.js)
const __dirname =
  typeof import.meta.dir === "string" ? import.meta.dir : dirname(fileURLToPath(import.meta.url));

// Project root is where the user runs the command (current working directory)
const PROJECT_ROOT = process.cwd();
const DOCKER_DIR = join(PROJECT_ROOT, "docker/n8n");

// Templates location depends on whether running from source or built package
// - Source: packages/installer/src/services/ -> ../../templates
// - Built:  packages/installer/dist/         -> ../templates
function getTemplateDir(): string {
  // Try built package location first (../templates from dist/)
  const builtPath = join(__dirname, "../templates");
  if (existsSync(builtPath)) {
    return builtPath;
  }
  // Fall back to source location (../../templates from src/services/)
  return join(__dirname, "../../templates");
}

const TEMPLATE_DIR = getTemplateDir();

export interface N8nConfig {
  encryptionKey: string;
  host: string;
  port: number;
  protocol: string;
}

/**
 * Generate a cryptographically secure encryption key (64 hex characters)
 */
export function generateEncryptionKey(): string {
  return randomBytes(32).toString("hex");
}

/**
 * Create the .env file with n8n configuration
 */
export async function createEnvFile(config: N8nConfig): Promise<void> {
  const envContent = `# n8n Configuration
# Generated by n8n-local-deploy installer
# DO NOT COMMIT THIS FILE

N8N_HOST=${config.host}
N8N_PORT=${config.port}
N8N_PROTOCOL=${config.protocol}
N8N_ENCRYPTION_KEY=${config.encryptionKey}
`;

  const envPath = join(DOCKER_DIR, ".env");

  // Ensure directory exists
  await mkdir(DOCKER_DIR, { recursive: true });

  // Write env file with restricted permissions
  await writeFile(envPath, envContent, { mode: 0o600 });
}

/**
 * Copy docker-compose.yml template to docker/n8n directory
 */
export async function copyDockerCompose(): Promise<void> {
  const templatePath = join(TEMPLATE_DIR, "docker-compose.yml");
  const targetPath = join(DOCKER_DIR, "docker-compose.yml");

  // Ensure directory exists
  await mkdir(DOCKER_DIR, { recursive: true });

  await copyFile(templatePath, targetPath);
}

/**
 * Read the existing .env file if it exists
 */
export async function readEnvFile(): Promise<N8nConfig | null> {
  const envPath = join(DOCKER_DIR, ".env");

  if (!existsSync(envPath)) {
    return null;
  }

  const content = await readFile(envPath, "utf-8");
  const lines = content.split("\n");

  const config: Partial<N8nConfig> = {};

  for (const line of lines) {
    const [key, value] = line.split("=");
    if (key === "N8N_HOST") config.host = value;
    if (key === "N8N_PORT") config.port = parseInt(value, 10);
    if (key === "N8N_PROTOCOL") config.protocol = value;
    if (key === "N8N_ENCRYPTION_KEY") config.encryptionKey = value;
  }

  if (config.encryptionKey && config.host && config.port && config.protocol) {
    return config as N8nConfig;
  }

  return null;
}

/**
 * Check if docker-compose.yml exists in the docker directory
 */
export function dockerComposeExists(): boolean {
  return existsSync(join(DOCKER_DIR, "docker-compose.yml"));
}

/**
 * Check if .env file exists
 */
export function envFileExists(): boolean {
  return existsSync(join(DOCKER_DIR, ".env"));
}

/**
 * Get the path to the docker directory
 */
export function getDockerDir(): string {
  return DOCKER_DIR;
}

/**
 * Create default configuration
 */
export function createDefaultConfig(): N8nConfig {
  return {
    encryptionKey: generateEncryptionKey(),
    host: "localhost",
    port: 8443,
    protocol: "https",
  };
}
