# n8n Local Installer Task Automation
# Provides development, testing, and maintenance tasks

version: "3"

# Path to ai-toolkit tasks in node_modules
vars:
  TASK_LIB: node_modules/@northbridge-security/ai-toolkit/tasks

# Include shared task libraries
includes:
  # Namespaced specialized tasks
  git:
    taskfile: "{{.TASK_LIB}}/git.yml"
    optional: true

  yaml:
    taskfile: "{{.TASK_LIB}}/yaml.yml"
    optional: true

  markdown:
    taskfile: "{{.TASK_LIB}}/markdown.yml"
    optional: true

  json:
    taskfile: "{{.TASK_LIB}}/json.yml"
    optional: true

  bash:
    taskfile: "{{.TASK_LIB}}/bash.yml"
    optional: true

  gotask:
    taskfile: "{{.TASK_LIB}}/gotask.yml"
    optional: true

  claude:
    taskfile: "{{.TASK_LIB}}/claude.yml"
    optional: true

  op:
    taskfile: "{{.TASK_LIB}}/onepassword.yml"
    optional: true

  # Project-specific tasks
  n8n:
    taskfile: ./scripts/tasks/n8n.yml
    dir: .
    optional: true

tasks:
  setup:
    desc: "Install/upgrade all required tools via Homebrew"
    silent: true
    cmds:
      - |
        set -euo pipefail

        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        echo -e "${CYAN}Installing/upgrading required tools${NC}"
        echo ""

        # Install or upgrade bun
        if brew list oven-sh/bun/bun &>/dev/null; then
          echo -e "${GREEN}Running:${NC} brew upgrade oven-sh/bun/bun"
          brew upgrade oven-sh/bun/bun 2>/dev/null || echo -e "${YELLOW}[SKIP]${NC} bun already at latest version"
        else
          echo -e "${GREEN}Running:${NC} brew install oven-sh/bun/bun"
          brew install oven-sh/bun/bun
          echo -e "${GREEN}✓${NC} bun installed"
        fi

        # Install or upgrade go-task
        if brew list go-task &>/dev/null; then
          echo -e "${GREEN}Running:${NC} brew upgrade go-task"
          brew upgrade go-task 2>/dev/null || echo -e "${YELLOW}[SKIP]${NC} go-task already at latest version"
        else
          echo -e "${GREEN}Running:${NC} brew install go-task"
          brew install go-task
          echo -e "${GREEN}✓${NC} go-task installed"
        fi

        # Install or upgrade semgrep
        if brew list semgrep &>/dev/null; then
          echo -e "${GREEN}Running:${NC} brew upgrade semgrep"
          brew upgrade semgrep 2>/dev/null || echo -e "${YELLOW}[SKIP]${NC} semgrep already at latest version"
        else
          echo -e "${GREEN}Running:${NC} brew install semgrep"
          brew install semgrep
          echo -e "${GREEN}✓${NC} semgrep installed"
        fi

        echo ""
        echo -e "${GREEN}Running:${NC} bun install"
        bun install

        echo ""
        echo -e "${GREEN}✓${NC} Setup complete"

  skills:
    desc: "Copy local skills to global Claude settings (~/.claude/skills/)"
    silent: true
    cmds:
      - |
        set -euo pipefail

        GREEN='\033[0;32m'
        RED='\033[0;31m'
        CYAN='\033[0;36m'
        NC='\033[0m'

        SOURCE_DIR=".claude/skills"
        TARGET_DIR="$HOME/.claude/skills"

        if [ ! -d "$SOURCE_DIR" ]; then
          echo -e "${RED}✗${NC} Local skills directory not found at $SOURCE_DIR" >&2
          exit 1
        fi

        mkdir -p "$TARGET_DIR"

        echo -e "${CYAN}Copying skills to $TARGET_DIR${NC}"
        cp -R "$SOURCE_DIR"/* "$TARGET_DIR/"

        echo ""
        echo -e "${GREEN}✓${NC} Skills installed:"
        ls -1 "$TARGET_DIR" | while read skill; do
          echo "  - $skill"
        done

  start:
    desc: "Start OrbStack and n8n container"
    silent: true
    cmds:
      - |
        set -euo pipefail

        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        RED='\033[0;31m'
        NC='\033[0m'

        # Ensure OrbStack is running
        if ! pgrep -q OrbStack; then
          echo -e "${GREEN}Running:${NC} open -a OrbStack"
          open -a OrbStack
          echo -e "${YELLOW}Waiting for OrbStack to start...${NC}"
          sleep 5
        else
          echo -e "${GREEN}✓${NC} OrbStack is running"
        fi

        # Check if n8n container exists
        if ! docker compose -f docker/n8n/docker-compose.yml ps -a --format json 2>/dev/null | grep -q n8n; then
          echo -e "${RED}✗${NC} n8n not installed. Run: task install:local"
          exit 1
        fi

        # Start container if not running
        if ! docker compose -f docker/n8n/docker-compose.yml ps --format json 2>/dev/null | grep -q '"running"'; then
          echo -e "${GREEN}Running:${NC} docker compose up -d"
          docker compose -f docker/n8n/docker-compose.yml up -d
          echo -e "${GREEN}✓${NC} n8n container started"
        else
          echo -e "${GREEN}✓${NC} n8n container already running"
        fi

  install:
    desc: "Install n8n with Cloudflare Tunnel (DOMAIN=x SUBDOMAIN=y FORCE=1)"
    aliases: [i]
    cmds:
      - bun run install:n8n {{if .FORCE}}--force{{end}} {{if .DOMAIN}}--domain {{.DOMAIN}}{{end}} {{if .SUBDOMAIN}}--subdomain {{.SUBDOMAIN}}{{end}}

  install:local:
    desc: "Install n8n for local access only (no tunnel)"
    aliases: [il]
    cmds:
      - bun run install:n8n --local {{if .FORCE}}--force{{end}}

  uninstall:
    desc: "Uninstall n8n from OrbStack"
    aliases: [u]
    cmds:
      - bun run uninstall:n8n

  status:
    desc: "Check n8n installation status"
    aliases: [s]
    cmds:
      - bun run status

  test:iq:
    desc: "Run Installation Qualification tests"
    aliases: [iq]
    cmds:
      - bun run test:iq

  test:oq:
    desc: "Run Operational Qualification tests"
    aliases: [oq]
    cmds:
      - bun run test:oq

  test:
    desc: "Run all validation tests (IQ + OQ)"
    aliases: [t]
    cmds:
      - bun run test:validate

  typecheck:
    desc: "Run TypeScript type checking"
    aliases: [tc]
    cmds:
      - bun run typecheck

  lint:
    desc: "Run Biome linter and formatter checks"
    aliases: [l]
    cmds:
      - bun run lint

  lint:fix:
    desc: "Auto-fix lint and format issues"
    aliases: [lf]
    cmds:
      - bun run lint:fix

  security:
    desc: "Run Semgrep security scan"
    aliases: [sec]
    cmds:
      - bun run security

  qa:
    desc: "Run all QA checks (lint, typecheck, security, tests)"
    cmds:
      - task: lint
      - task: typecheck
      - task: security
      - task: test

  default:
    desc: "Show available tasks"
    aliases: [help, h]
    silent: true
    cmds:
      - |
        # Color codes
        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        BLUE='\033[0;34m'
        BOLD='\033[1m'
        NC='\033[0m'

        echo -e "${BOLD}n8n Local Installer${NC}"
        echo ""
        echo "Command                          Alias     Description"
        echo "─────────────────────────────────────────────────────────────────────────────────────────────────"
        echo -e "${BOLD}Setup:${NC}"
        echo -e "  ${GREEN}task setup${NC}                               Install/upgrade tools (bun, go-task, semgrep)"
        echo -e "  ${GREEN}task skills${NC}                              Copy local skills to ~/.claude/skills/"
        echo ""
        echo -e "${BOLD}Installation:${NC}"
        echo -e "  ${GREEN}task install${NC}                   ${YELLOW}i${NC}         Install n8n with Cloudflare Tunnel    DOMAIN=x SUBDOMAIN=y FORCE=1"
        echo -e "  ${GREEN}task install:local${NC}             ${YELLOW}il${NC}        Install n8n for local access only"
        echo -e "  ${GREEN}task start${NC}                               Start OrbStack and n8n container"
        echo -e "  ${GREEN}task uninstall${NC}                 ${YELLOW}u${NC}         Uninstall n8n from OrbStack"
        echo -e "  ${GREEN}task status${NC}                    ${YELLOW}s${NC}         Check n8n installation status"
        echo ""
        echo -e "${BOLD}Testing:${NC}"
        echo -e "  ${GREEN}task test${NC}                      ${YELLOW}t${NC}         Run all validation tests (IQ + OQ)"
        echo -e "  ${GREEN}task test:iq${NC}                   ${YELLOW}iq${NC}        Run Installation Qualification tests"
        echo -e "  ${GREEN}task test:oq${NC}                   ${YELLOW}oq${NC}        Run Operational Qualification tests"
        echo ""
        echo -e "${BOLD}Development:${NC}"
        echo -e "  ${GREEN}task typecheck${NC}                 ${YELLOW}tc${NC}        Run TypeScript type checking"
        echo -e "  ${GREEN}task lint${NC}                      ${YELLOW}l${NC}         Run Biome linter and formatter"
        echo -e "  ${GREEN}task lint:fix${NC}                  ${YELLOW}lf${NC}        Auto-fix lint and format issues"
        echo -e "  ${GREEN}task security${NC}                  ${YELLOW}sec${NC}       Run Semgrep security scan"
        echo -e "  ${GREEN}task qa${NC}                                  Run all QA checks"
        echo ""
        echo -e "${BOLD}n8n Operations:${NC}"
        echo -e "  ${GREEN}task n8n:logs${NC}                            View n8n container logs"
        echo -e "  ${GREEN}task n8n:restart${NC}                         Restart n8n container"
        echo -e "  ${GREEN}task n8n:shell${NC}                           Open shell in n8n container"
        echo -e "  ${GREEN}task n8n:open${NC}                            Open n8n in browser"
        echo ""
        echo -e "${BOLD}Task Libraries:${NC}"
        echo -e "  ${GREEN}task git:<command>${NC}                       Git operations                    See: task git:help"
        echo -e "  ${GREEN}task yaml:<command>${NC}             ${YELLOW}yml${NC}       YAML linting & validation         See: task yaml:help"
        echo -e "  ${GREEN}task markdown:<command>${NC}         ${YELLOW}md${NC}        Markdown linting & validation     See: task markdown:help"
        echo ""
        echo -e "${BLUE}Run 'task --list' to see all available tasks${NC}"
